### ISSUE TITLE
Document and type headers

### ISSUE THREAD

**Issue by sofianegargouri** [Svehla/openapi-typed-express#2]
Hi mate ! Great work with the lib, I love it.

I think one missing thing is the documentation of headers, since those are used in a lot of cases to provide authentication for example.
Putting them in a global config is not enough since some endpoints would require them and other would not (you would not provide your Bearer token on a signin endpoint for example)

**Comment by Svehla** [comment]
Hi 👋

To be honest, I hadn't noticed that someone was using this repository. :D I came back after some time and did a substantial refactor... If you're using this repo, I could add validation + swagger for headers as well. Is this still relevant for you?

I apologize for changing the public API, but now it's much nicer (at least I hope so).

**Comment by sofianegargouri** [comment]
Hi ! 
I haven't been using it since this was a needed feature for my project, but thanks for the offer !
